x=input("enter first number:")
y=input("enter second number:")
print(float(x)+float(y))
print(float(x)-float(y))
print(float(x)*float(y))
print(float(x)/float(y))
print(float(x)**float(y))
print(float(x)%float(y))
print(float(x)//float(y))