a=1
b="Chintan"
c='Boghani'
d=True
e=None
f=complex(8,-2)
print(a)
print(b)
print(b+c)
print(f)
print(type(a))
print(type(b))
print(type(d))
print(type(e))
print(type(f))
list1=[8,2.3,[-4,5],["apple,banana"]]
print(list1)
tuple1=(("parrot","sparrow"),("lion","tiger"),"shreeji")
print(tuple1)
dict1={"name":"Chintan","age":19,'canvote':True}
print(dict1)